name: Diagnostika SIS

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test SIS
        run: |
          URL="https://is.cuni.cz/studium/rozvrhng/roz_student_macro.php?skr=2026&sem=1&fak=11110&druh=MGR&kruh=1003&b=Zobraz+MGR.MED.1.LEK.a.1003.P"

          echo "===== RESPONSE ====="

          curl -v \
            -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/140.0.0.0 Safari/537.36" \
            "$URL" \
            -o response.html \
            2> headers.txt

          echo ""
          echo "===== CURL ====="
          cat headers.txt

          echo ""
          echo "===== HTML ====="
          head -50 response.html

      - name: Upload výsledků
        uses: actions/upload-artifact@v4
        with:
          name: sis-diagnostika
          path: |
            response.html
            headers.txt
